Bumps in garden : ign-plugin2
ignition-tooling/gazebodistro pull request #81
Opened 2022-04-06 23:06 UTC by methylDragon

See https://github.com/ignition-tooling/release-tools/issues/685

2022-04-06 23:30 UTC, chapulina approved these changes

2022-04-07 14:26 UTC, j-rivero requested changes
Thanks for the PR @methylDragon ! This repository is not very friendly with respect to propagate changes to other files in Garden using declaring ign-plugin as a dependency. Does any other of the bumps in Garden at this time is going to use ign-plugin? Using a quick check for guidance:

```
gazebodistro on  master [?] ❯ grep -R utils * | awk '{ print $1}' | sort | uniq 
collection-edifice.yaml:
collection-fortress.yaml:
collection-garden.yaml:
ign-common4.yaml:
ign-common5.yaml:
ign-fuel-tools8.yaml:
ign-gazebo5.yaml:
ign-gazebo6.yaml:
ign-gazebo7.yaml:
ign-gui5.yaml:
ign-gui6.yaml:
ign-gui7.yaml:
ign-launch4.yaml:
ign-launch5.yaml:
ign-launch6.yaml:
ign-math7.yaml:
ign-msgs9.yaml:
ign-physics4.yaml:
ign-physics5.yaml:
ign-physics6.yaml:
ign-plugin2.yaml:
ign-rendering5.yaml:
ign-rendering6.yaml:
ign-rendering7.yaml:
ign-sensors5.yaml:
ign-sensors6.yaml:
ign-sensors7.yaml:
ign-transport10.yaml:
ign-transport11.yaml:
ign-transport12.yaml:
ign-utils1.yaml:
ign-utils2.yaml:
sdformat11.yaml:
sdformat12.yaml:
sdformat13.yaml:
```

At least the collection-garden file needs to be change IMHO. Could you please check if we need to bump any other? Thanks!

2022-04-07 23:11 UTC, methylDragon commented
Erm... There will be a bump following this one that will bump ign-cmake3, ign-utils2, ign-tools2, ign-plugin2, which means practically every library will get bumped :/

But in this first wave of bump ign-cmake3, ign-util2, ign-plugin2, which no other libraries will be relying on, in my understanding (since they'll be relying on `ign-plugin1`.

Hopefully I got that right, I'm still a little unfamiliar with the ign libs

2022-04-08 00:49 UTC, chapulina commented
Just to add to what @methylDragon said, we'll be opening PRs for each library separately even for the next wave, because that makes it easier to merge them in order. It's like we did for the previous Garden bumps:

https://github.com/ignition-tooling/gazebodistro/pulls?q=is%3Apr+is%3Aclosed+bumps+in+garden

2022-04-08 13:52 UTC, merged